apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: 005744789143.dkr.ecr.us-east-1.amazonaws.com/gti778/maria-db:latest
          ports:
            - containerPort: 3360
          env:
            - name: DBPort
              value: "3360"
            - name: DBUser
              value: "test"
            - name: DBRootPassword
              value: "Password123!"
            - name: MYSQL_DATABASE
              value: "Pizzas"
          resources:
            requests:
              cpu: "2"
              memory: "3Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 5
            periodSeconds: 10
